import test from 'node:test'; import assert from 'node:assert/strict'; import { CandidateSocialCopySchema, CreateRenderSchema, CreateSourceSchema, UpdateCandidateSchema, validTransition } from './index.js';
test('platform source requires provider', () => assert.throws(() => CreateSourceSchema.parse({sourceType:'platform_url', mediaType:'video', uri:'https://example.test/v'})));
test('source types validate', () => { for (const sourceType of ['upload','direct_url','platform_url'] as const) assert.equal(CreateSourceSchema.parse({sourceType,mediaType:'audio',uri:'https://example.test/a', ...(sourceType==='platform_url'?{provider:'youtube'}:{})}).sourceType,sourceType); });
test('job state transitions are constrained', () => { assert.equal(validTransition('queued','processing'),true); assert.equal(validTransition('completed','processing'),false); });
test('candidate copy and review updates validate', () => { assert.deepEqual(CandidateSocialCopySchema.parse({headline:'Headline',caption:'Caption',hashtags:['#Axios']}), {headline:'Headline',caption:'Caption',hashtags:['#Axios'], headlineCards:[], nameTags:[]}); assert.equal(UpdateCandidateSchema.parse({reviewStatus:'accepted',startSeconds:1,endSeconds:2}).reviewStatus,'accepted'); });
test('candidate copy preserves editor transcript and subtitle state', () => { const copy = CandidateSocialCopySchema.parse({headline:'Headline',caption:'Caption',hashtags:[],transcriptEdits:{words:[{id:'s0w0',text:'Edited'}]},subtitlePosition:{xPercent:52,yPercent:64,alignment:'center'}}); assert.deepEqual(copy.transcriptEdits, {words:[{id:'s0w0',text:'Edited'}]}); assert.deepEqual(copy.subtitlePosition, {xPercent:52,yPercent:64,alignment:'center'}); });

test('headline cards validate bounded timing, color, shape, and position', () => { const copy = CandidateSocialCopySchema.parse({headline:'Headline',caption:'Caption',hashtags:[],headlineCards:[{id:'card-1',text:'A key point',startSeconds:0,endSeconds:3,color:'purple'}]}); assert.equal(copy.headlineCards[0].color, 'purple'); assert.equal(copy.headlineCards[0].shape, 'rounded'); assert.equal(copy.headlineCards[0].xPercent, 50); assert.equal(copy.headlineCards[0].yPercent, 70); assert.equal(copy.headlineCards[0].widthPercent, 84); assert.equal(copy.headlineCards[0].heightPercent, 21); assert.equal(copy.headlineCards[0].placementCustomized, false); const white = CandidateSocialCopySchema.parse({headline:'Headline',caption:'Caption',hashtags:[],headlineCards:[{id:'card-2',text:'White card',startSeconds:0,endSeconds:1,color:'white',shape:'pill',xPercent:50,yPercent:53}]}); assert.equal(white.headlineCards[0].color, 'white'); assert.equal(white.headlineCards[0].shape, 'pill'); assert.throws(() => CandidateSocialCopySchema.parse({headline:'Headline',caption:'Caption',hashtags:[],headlineCards:[{id:'card-1',text:'Too long',startSeconds:4,endSeconds:3,color:'navy'}]})); });
test('name tags validate default white styling and separate identity fields', () => { const copy = CandidateSocialCopySchema.parse({headline:'Headline',caption:'Caption',hashtags:[],nameTags:[{id:'tag-1',name:'Mike Allen',title:'Co-founder, Axios',startSeconds:0,endSeconds:3}]}); assert.equal(copy.nameTags[0].color, 'white'); assert.equal(copy.nameTags[0].xPercent, 32); assert.equal(copy.nameTags[0].widthPercent, 58); assert.equal(copy.nameTags[0].heightPercent, 14); assert.throws(() => CandidateSocialCopySchema.parse({headline:'Headline',caption:'Caption',hashtags:[],nameTags:[{id:'tag-1',name:'Mike Allen',title:'Co-founder, Axios',startSeconds:3,endSeconds:1}]})); });
test('render framing, background, and logo placement default to the Axios template', () => { assert.equal(CreateRenderSchema.parse({}).fitMode, 'cover'); assert.equal(CreateRenderSchema.parse({fitMode:'contain'}).fitMode, 'contain'); assert.equal(CreateRenderSchema.parse({}).background, 'dark_blue'); assert.equal(CreateRenderSchema.parse({background:'blurred'}).background, 'blurred'); assert.equal(CreateRenderSchema.parse({}).logoPosition, 'top-left'); assert.equal(CreateRenderSchema.parse({}).logoAssetId, null); assert.equal(CreateRenderSchema.parse({logoPosition:'bottom-center'}).logoPosition, 'bottom-center'); assert.throws(() => CreateRenderSchema.parse({logoPosition:'freeform'})); const copy = CandidateSocialCopySchema.parse({ headline: '', caption: '', hashtags: [], logoPositionPercent: { x: 27.5, y: 63 } }); assert.deepEqual(copy.logoPositionPercent, { x: 27.5, y: 63 }); assert.throws(() => CandidateSocialCopySchema.parse({ headline: '', caption: '', hashtags: [], logoPositionPercent: { x: 101, y: 63 } })); });
test('create render preserves and validates the authoritative render spec', () => { const renderSpec = { schema: 'axios.clip.render-spec.v1', rendererTarget: 'headless_chromium', dimensions: { width: 1080, height: 1920, fps: 30 }, source: { trim: { startSeconds: 1, endSeconds: 4 } }, video: { fitMode: 'contain' }, logo: { enabled: true }, headlineCards: [{ id: 'card', geometryPercent: { x: 50 } }], nameTags: [], captions: { lines: [] }, futureField: 'preserved' }; const parsed = CreateRenderSchema.parse({ renderSpec }); assert.deepEqual(parsed.renderSpec, renderSpec); assert.throws(() => CreateRenderSchema.parse({ renderSpec: { ...renderSpec, dimensions: { ...renderSpec.dimensions, fps: 60 } } })); });
